### ISSUE TITLE
Illegal access reflection

### ISSUE THREAD

**Issue by aelgn** [javers/javers#1091]
Javers uses reflection `setAccessible` on types, see JaversMember:95. If you want to diff a class with non-public fields of a java.lang type (like String, Locale etc...) `setAccessible` is considered an illegal access operation.
This has just resulted in runtime warnings but with java 16 out the default is to deny these operations. It is still possible to override this behavior with the vm arg `--illegal-access=warn`, but this will be removed in a future JVM release.

A more granular way is to add the module import with vm args for each sub module in java.base `--add-open`.
But this will require all downstream projects to change their runtime config, which is much more cumbersome than to declare the modules in a `module-info.java` file in javers.

https://github.com/javers/javers/issues/911

**Steps To Reproduce**
* create diffable dto class with a private final Locale member
* launch with java 16
* diff it
-> exception: `java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.util.Map java.util.Locale.CONSTANT_LOCALES accessible: module java.base does not "opens java.util" to unnamed module @1c53fd30`
```
static class Qwop {
    private final Locale l;
    Qwop(final Locale l) {
        this.l = l;
    }
}
...
final Javers javers = JaversBuilder.javers().build();
javers.compare(new Qwop(Locale.US), new Qwop(Locale.CHINA));
```

**Javers' Version**
5.14.0 & 6.1.0

**Comment by bartoszwalacik** [comment]
already fixed in Javers 6.0, see https://github.com/javers/javers/issues/911

**Comment by bartoszwalacik** [comment]
ok, I see that you have referenced https://github.com/javers/javers/issues/911 in your report, so why this issue?

**Comment by aelgn** [comment]
@bartoszwalacik hi, ah yes. I tested it with 6.1.0 too but still reproduced - will update the issue to reflect this

**Comment by dmitry-weirdo** [comment]
Most probably is an issue with Java 16, I have exactly the same bug, also on 6.1.0. The same code is working under Java 15.

**Comment by bartoszwalacik** [comment]
Could be, it would be nice if you guys come up with a PR to fix this issue with Java 16.

**Comment by bartoszwalacik** [comment]
@dmitry-weirdo how to reproduce this issue with Java 16?

**Comment by aelgn** [comment]
@bartoszwalacik see reproducible steps in the issue above. It is using Locale as an example, but any Type from the java std lib will have the same issue if it contains private members, since javers tries to .setAccessible on them and java16 prevents that as a default. Maybe leverage the jackson serialization lib? I guess they solved it by creating custom serializers for alot of the data types in java std lib, and they also have extnesion modules for eg. Guava types.

**Comment by bartoszwalacik** [comment]
confirmed, javers doesn't work on java 16

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final long java.time.LocalDate.serialVersionUID accessible: module java.base does not "opens java.time" to unnamed module @59dfd65b
```

**Comment by bartoszwalacik** [comment]
fixed in 6.2.0

**Comment by dmitry-weirdo** [comment]
Unfortunately, still not fixed in 6.2.2, looks like it fails on comparing `java.util.Locale` fields :(

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private transient sun.util.locale.BaseLocale java.util.Locale.baseLocale accessible: module java.base does not "opens java.util" to unnamed module @1e6d1014

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at org.javers.common.reflection.JaversMember.setAccessibleIfNecessary(JaversMember.java:95)
	at org.javers.common.reflection.JaversMember.<init>(JaversMember.java:47)
	at org.javers.common.reflection.JaversMember.<init>(JaversMember.java:39)
	at org.javers.common.reflection.JaversField.<init>(JaversField.java:17)
	at org.javers.common.reflection.JaversFieldFactory.createJField(JaversFieldFactory.java:43)
	at org.javers.common.reflection.JaversFieldFactory.getAllFields(JaversFieldFactory.java:31)
	at org.javers.common.reflection.ReflectionUtil.getAllFields(ReflectionUtil.java:125)
	at org.javers.common.reflection.ReflectionUtil.getAllPersistentFields(ReflectionUtil.java:110)
	at org.javers.core.metamodel.scanner.FieldBasedPropertyScanner.getMembers(FieldBasedPropertyScanner.java:19)
	at org.javers.core.metamodel.scanner.PropertyScanner.scan(PropertyScanner.java:25)
	at org.javers.core.metamodel.scanner.ClassScanner.scan(ClassScanner.java:19)
	at org.javers.core.metamodel.type.TypeFactory$JavaRichType.lambda$new$0(TypeFactory.java:195)
	at org.javers.core.metamodel.type.TypeFactory$JavaRichType.getScan(TypeFactory.java:208)
	at org.javers.core.metamodel.type.TypeFactory.inferFromAnnotations(TypeFactory.java:163)
	at org.javers.core.metamodel.type.TypeFactory.lambda$infer$4(TypeFactory.java:108)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.javers.core.metamodel.type.TypeFactory.infer(TypeFactory.java:108)
	at org.javers.core.metamodel.type.TypeMapper.lambda$getJaversType$0(TypeMapper.java:121)
	at org.javers.core.metamodel.type.TypeMapperEngine.computeIfAbsent(TypeMapperEngine.java:103)
	at org.javers.core.metamodel.type.TypeMapper.getJaversType(TypeMapper.java:121)
	at org.javers.core.metamodel.type.ManagedClassFactory.lambda$convert$2(ManagedClassFactory.java:54)
	at org.javers.core.metamodel.type.JaversProperty.getType(JaversProperty.java:27)
	at org.javers.core.metamodel.type.JaversProperty.isEntityType(JaversProperty.java:31)
	at org.javers.core.metamodel.type.InstanceIdFactory.dehydratedLocalId(InstanceIdFactory.java:61)
	at org.javers.core.metamodel.type.InstanceIdFactory.dehydratedLocalId(InstanceIdFactory.java:92)
	at org.javers.core.metamodel.type.InstanceIdFactory.create(InstanceIdFactory.java:23)
	at org.javers.core.metamodel.type.EntityType.createIdFromInstance(EntityType.java:123)
	at org.javers.core.metamodel.object.GlobalIdFactory.createId(GlobalIdFactory.java:52)
	at org.javers.core.graph.LiveCdoFactory.create(LiveCdoFactory.java:38)
	at org.javers.core.graph.EdgeBuilder.lambda$createMultiEdge$0(EdgeBuilder.java:53)
	at org.javers.core.metamodel.type.CollectionType.mapToSet(CollectionType.java:64)
	at org.javers.core.metamodel.type.SetType.map(SetType.java:28)
	at org.javers.core.graph.EdgeBuilder.createMultiEdge(EdgeBuilder.java:62)
	at org.javers.core.graph.ObjectGraphBuilder.buildMultiEdges(ObjectGraphBuilder.java:112)
	at org.javers.core.graph.ObjectGraphBuilder.buildEdges(ObjectGraphBuilder.java:92)
	at org.javers.core.graph.ObjectGraphBuilder.buildGraphFromCdo(ObjectGraphBuilder.java:62)
	at org.javers.core.graph.ObjectGraphBuilder.buildGraph(ObjectGraphBuilder.java:51)
	at org.javers.core.graph.LiveGraphFactory.createLiveGraph(LiveGraphFactory.java:38)
	at org.javers.core.diff.DiffFactory.buildGraph(DiffFactory.java:102)
	at org.javers.core.diff.DiffFactory.compare(DiffFactory.java:55)
	at org.javers.core.JaversCore.compare(JaversCore.java:176)
```

My Java version:
```
>java -version
java version "16.0.1" 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

**Comment by bartoszwalacik** [comment]
`Locale` should be added to `WellKnownValueTypes`, please contribute a PR

**Comment by bartoszwalacik** [comment]
The problem with `java.util.Locale` is fixed in 6.2.3

**Comment by adrianboimvaser** [comment]
Hi, I'm having the same problem with `java.time.MonthDay.month`:
```
Unable to make field private final int java.time.MonthDay.month accessible: module java.base does not "opens java.time" to unnamed module @610f7aa
```

**Comment by bartoszwalacik** [comment]
@adrianboimvaser please open a new issue for that. Please push a failing test case
