### ISSUE TITLE
NullPointerException when trying to parse parseUnboundedValueObject of a Map<String, Object>

### ISSUE THREAD

**Issue by xytrams** [javers/javers#1099]
**Clear description of my expectations versus reality**
I am using Javers with SpringBoot and Mongo DB. The object I'm saving in the Mongo DB is not of a flat structure. In fact it is quite complex:
`public class A {
	private final B b;
	private final C c;
	private final Map<String, List<E>> map;
}
`
My repository class looks like this:
`
@JaversSpringDataAuditable
public interface ARepository extends MongoRepository<A, String>{

    @Query(value = "{'b.id' : ?0 }")
	public Optional<A> findById(String id);
}

`
I have simple service where I'd like to retrieve some info about object: who created/when etc

`
@Service
@RequiredArgsConstructor
public class AService {
	private final Javers javers;

	public String getInitSnapshot(String id) {
		QueryBuilder query = QueryBuilder.byClass(A.class);
		List<CdoSnapshot> snapshots = javers.findSnapshots(query.build());

		return javers.getJsonConverter().toJson(snapshots);
	}
}
`

And I have a tests to try it out:

`
@ActiveProfiles("test")
@SpringBootTest
@Slf4j
class AServiceTest {
	@Autowired
	private ARepository repository;
	
	@Autowired
	private AService service;

	
	@Test
	void testJavers() {
		repository.save(buildEntity());
		
		String info = service.getInitSnapshot("id");
		
		log.info(info);
		
		assertNotNull(info);
	}
}
`

Well, this doesn't work.
When Javers try to parse UnboundedValueObjectId of a Map<String, List<E>> .

**Steps To Reproduce**
I have a **runnable test case ** which isolates the bug and allows Javers Core Team to easily reproduce it. I have pushed this test case to my fork of this repository:

Please feel free to fork out 
https://github.com/xytrams/javers-error

**Javers' Version**
6.1.1

**Additional context**
...
Would be great if it could be fixed/dealt with.

**Comment by bartoszwalacik** [comment]
@xytrams please create a PR with your test case to this repository. Follow the existing tests structure.

**Comment by xytrams** [comment]
https://github.com/javers/javers/pull/1104
I tried to do my best to demonstrate the problem

**Comment by bartoszwalacik** [comment]
is it what you get?

```
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(java.lang.String)" is null

	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.parseUnboundedValueObject(GlobalIdTypeAdapter.java:49)
```

**Comment by xytrams** [comment]
No, my exception:

java.lang.NullPointerException
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.parseUnboundedValueObject(GlobalIdTypeAdapter.java:49)
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.fromJson(GlobalIdTypeAdapter.java:44)
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.fromJson(GlobalIdTypeAdapter.java:19)
	at org.javers.core.json.JsonConverterBuilder.lambda$registerJsonTypeAdapterForType$4(JsonConverterBuilder.java:167)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotStateDeserializer.decodePropertyValue(CdoSnapshotStateDeserializer.java:76)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotStateDeserializer.lambda$deserialize$0(CdoSnapshotStateDeserializer.java:44)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotStateDeserializer.deserialize(CdoSnapshotStateDeserializer.java:42)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotTypeAdapter.deserializeSnapshotState(CdoSnapshotTypeAdapter.java:74)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotTypeAdapter.fromJson(CdoSnapshotTypeAdapter.java:60)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotTypeAdapter.fromJson(CdoSnapshotTypeAdapter.java:22)
	at org.javers.core.json.JsonConverterBuilder.lambda$registerJsonTypeAdapterForType$4(JsonConverterBuilder.java:167)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:975)
	at org.javers.core.json.JsonConverter.fromJson(JsonConverter.java:74)
	at org.javers.repository.mongo.MongoRepository.readFromDBObject(MongoRepository.java:208)
	at org.javers.repository.mongo.MongoRepository.queryForSnapshots(MongoRepository.java:353)
	at org.javers.repository.mongo.MongoRepository.getStateHistory(MongoRepository.java:134)
	at org.javers.repository.api.JaversExtendedRepository.getStateHistory(JaversExtendedRepository.java:149)
	at org.javers.repository.jql.SnapshotQueryRunner.queryForSnapshots(SnapshotQueryRunner.java:40)
	at org.javers.repository.jql.QueryRunner.queryForSnapshots(QueryRunner.java:41)
	at org.javers.core.JaversCore.findSnapshots(JaversCore.java:200)
	at com.xytrams.javers.AService.getInitSnapshot(AService.java:23)
	at com.xytrams.javers.AServiceTest.testJavers(AServiceTest.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**Comment by bartoszwalacik** [comment]
Fixed in 6.3.0

**Comment by zzakir** [comment]
This is still happening in version 6.4.2. It's very random as well. Hard to reproduce. But the exception is exactly the same.

**Comment by alabotski** [comment]
I get this error in 6.6.0

```
@Entity
@Table(name = "limitation")
@TypeName("Limit")
public class LimitEntity extends BaseEntity {
...
  @OneToMany(mappedBy = "limit", orphanRemoval = true, cascade = CascadeType.ALL)
  @ToString.Exclude
  @Builder.Default
  private Set<LimitRangeEntity> limitRanges = new HashSet<>();
....
}

@Entity
@Table(name = "limitation_range")
@TypeName("LimitRange")
@ValueObject
public class LimitRangeEntity extends BaseEntity {
...
  @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH, CascadeType.DETACH})
  @JoinColumn(name = "limit_id", nullable = false)
  @ToString.Exclude
  @DiffIgnore
  private LimitEntity limit;
...
}

@Repository
@JaversSpringDataAuditable
public interface LimitRepository extends JpaRepository<LimitEntity, UUID>, QuerydslPredicateExecutor<LimitEntity> {
}

@Repository
public interface LimitRangeRepository extends JpaRepository<LimitRangeEntity, UUID>, QuerydslPredicateExecutor<LimitRangeEntity> {

}

  @Transactional
  public void addAudit(AuditEntity auditEntity) {
    auditRepository.save(auditEntity);
  }

  public List<Shadow<LimitEntity>> findShadows(UUID limitId) {
    var limitEntity = dataBaseService.findLimit(limitId);
    var queryBuilder = QueryBuilder.byInstanceId(limitId, LimitEntity.class)
        //.withChildValueObjects()
        //.withScopeDeepPlus()
        //.withScopeCommitDeep()
        .build();
    List<Shadow<LimitEntity>> shadowLimits = javers.findShadows(queryBuilder);
    return shadowLimits;
  }
```

**Comment by bartoszwalacik** [comment]
@alabotski , please write and push a failing test case , see https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting

**Comment by alabotski** [comment]
@bartoszwalacik 

https://github.com/alabotski/demo/tree/main/javers-json-npe

So my global question
Why I can't  see commits when changed child entities?

I expect it should be 5 here (init commit and 4 change commit)
https://github.com/alabotski/demo/blob/2c31654a6981218cc350bcbf5c258562650fef51/javers-json-npe/src/test/java/by/demo/ApplicationTest.java#L105

I used different options but it doesn't help me
```
        //.withChildValueObjects()
        //.withScopeDeepPlus()
        //.withScopeCommitDeep()
```

Then I tried your advice 
https://stackoverflow.com/questions/44386270/javers-not-detecting-changes-to-object-attributes-inside-a-collection

And try add ValueObject (see class LimitRangeEntity & LimitSignatureEnity and uncomment annotation) but have NPE error

PS Sorry for English.

**Comment by bartoszwalacik** [comment]
@alabotski a new test case should not be a separate java project (btw we don't use maven here). Please follow https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting and write a test case in the same way as we write test cases here

**Comment by alabotski** [comment]
Unfortunately, I didn’t work with groovy... Therefore, it won’t be possible to write a quick test... In the future, if there are any problems, I will write already within the rules

**Comment by bartoszwalacik** [comment]
@alabotski I encourage to learn groovy, writing tests in groovy is a pleasure. If you must write in Java in `src/test/java` but please follow the project structure

**Comment by bartoszwalacik** [comment]
if you will be ready please create a new Issue and a PR with your test case

**Comment by alabotski** [comment]
@bartoszwalacik can you give links with examples java test
spring jpa + javers

**Comment by bernardoappraiser** [comment]
> is it what you get?
> 
> ```
> java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(java.lang.String)" is null
> 
> 	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.parseUnboundedValueObject(GlobalIdTypeAdapter.java:49)
> ```





https://stackdev.space/questions/encountering-a-null-pointer-exception-in-android-while-parsing-data

**Comment by bartoszwalacik** [comment]
@alabotski see https://github.com/javers/javers/tree/master/javers-spring-boot-starter-sql/src/test/groovy/org/javers/spring/sql

**Comment by alabotski** [comment]
@bartoszwalacik 
Hi

What does your deleted comment mean?
@alabotski see https://github.com/javers/javers/tree/master/javers-spring-boot-starter-sql/src/test/groovy/org/javers/spring/sql
