### ISSUE TITLE
GlobalIdTypeAdapter parseValueObjectId NPE

### ISSUE THREAD

**Issue by alabotski** [javers/javers#1180]
Error reproduced when Entities have multiple nesting levels of child Entities

```
java.lang.NullPointerException
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.parseValueObjectId(GlobalIdTypeAdapter.java:54)
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.fromJson(GlobalIdTypeAdapter.java:42)
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.fromJson(GlobalIdTypeAdapter.java:19)
	at org.javers.core.json.JsonConverterBuilder.lambda$registerJsonTypeAdapterForType$4(JsonConverterBuilder.java:162)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotStateDeserializer.decodePropertyValue(CdoSnapshotStateDeserializer.java:76)
	at org.javers.core.json.typeadapter.commit.CdoSnapshotStateDeserializer.lambda$deserialize$0(CdoSnapshotStateDeserializer.java:44)
```
https://github.com/alabotski/javers/pull/1

**Comment by bartoszwalacik** [comment]
Hi, your PR should be targeted to this repository master and not your fork master, please change it

**Comment by alabotski** [comment]
Why close the task? If the bug is not fixed

**Comment by alabotski** [comment]
1. Described the task in the ticket - doesn't work for you 
2. Created a simple example - doesn't work for you 
3. Created a PR - again doesn't work for you

**Comment by alabotski** [comment]
https://github.com/javers/javers/pull/1181

**Comment by bartoszwalacik** [comment]
sorry, must be a mistake, your report is legit now, I will take a look

**Comment by bartoszwalacik** [comment]
Fixed in 6.6.2, @alabotski thanks for reporting

**Comment by zzakir** [comment]
@bartoszwalacik This error is still happening for me on version 6.6.2. I am using mongodb and the error is in the method 
**parseUnboundedValueObject**

`java.lang.NullPointerException: null
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.parseUnboundedValueObject(GlobalIdTypeAdapter.java:50) ~[javers-core-6.6.2.jar!/:na]
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.fromJson(GlobalIdTypeAdapter.java:45) ~[javers-core-6.6.2.jar!/:na]
	at org.javers.core.json.typeadapter.commit.GlobalIdTypeAdapter.fromJson(GlobalIdTypeAdapter.java:20) ~[javers-core-6.6.2.jar!/:na]
	at org.javers.core.json.JsonConverterBuilder.lambda$registerJsonTypeAdapterForType$4(JsonConverterBuilder.java:162) ~[javers-core-6.6.2.jar!/:na]`

**Comment by bartoszwalacik** [comment]
@zzakir it could be another issue, please report a new issue following this instruction https://github.com/javers/javers/blob/master/CONTRIBUTING.md#guidelines-for-bug-reporting
