### ISSUE TITLE
Illegal access reflection TimeZone ZoneRules, ZoneId and ZoneInfo.

### ISSUE THREAD

**Issue by gsabboz** [javers/javers#1200]
Javers doesn't work on java 16 with classes TimeZone ZoneRules, ZoneId, and ZoneInfo.
This issue is similar to https://github.com/javers/javers/issues/1091. 

I made a pull request for this #1201 

**Javers' Version**
6.6.3

**Comment by bartoszwalacik** [comment]
fixed in 6.6.6

**Comment by PandarinDev** [comment]
I assume that was meant to be 6.6.5 since the changelog on the website mentions this as a fix for 6.6.5. However, this issue is still present for the `YearMonth` class. Should I open a separate issue for this?

**Comment by opodrubailo** [comment]
@bartoszwalacik same question.
Got java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.time.ZoneRegion.id accessible for a ZoneId field.
Is there any workaround for this? Because I'm trying Javers on Java 17, where --illegal-access=warn is not supported

**Comment by opodrubailo** [comment]
@PandarinDev found a workaround - add VM option `--add-opens java.base/java.time=ALL-UNNAMED`
