### ISSUE TITLE
Javers integration with Cosmos Mongo DB

### ISSUE THREAD

**Issue by StefanoConoci** [javers/javers#1272]
Hi all,
I'm trying to integrate Javers in a Java Spring 2.7.8 micro-service with Cosmos Mongo DB as database.

The integration works as expected in my local environment where I connect to a "standard" Mongo DB instance (not Cosmos). However, whenever I deploy my micro-service to the Azure environment with Cosmos MongoDB, I receive an error whenever an audited object is created or modified. 

The error is the following:

```
2023-03-09T16:46:46.297895162Z com.mongodb.MongoQueryException: Query failed with error code 2 with name 'BadValue' and error message 'Error=2, Details='Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 03b951e1-8c89-4e0e-a534-143b289f8b8d; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 03b951e1-8c89-4e0e-a534-143b289f8b8d; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 03b951e1-8c89-4e0e-a534-143b289f8b8d; Reason: (Message: {"Errors":["The index path corresponding to the specified order-by item is excluded."]}
2023-03-09T16:46:46.297931364Z  at com.mongodb.internal.operation.FindOperation.lambda$execute$1(FindOperation.java:699)
2023-03-09T16:46:46.297935864Z  at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$2(OperationHelper.java:575)
2023-03-09T16:46:46.297940064Z  at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:600)
2023-03-09T16:46:46.297944365Z  at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:574)
2023-03-09T16:46:46.297948265Z  at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:600)
2023-03-09T16:46:46.297952665Z  at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:573)
2023-03-09T16:46:46.297957065Z  at com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:690)
2023-03-09T16:46:46.297960965Z  at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65)
2023-03-09T16:46:46.297965566Z  at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:722)
2023-03-09T16:46:46.297969466Z  at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:86)
2023-03-09T16:46:46.297973866Z  at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
2023-03-09T16:46:46.297977866Z  at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
2023-03-09T16:46:46.297981867Z  at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
2023-03-09T16:46:46.297985967Z  at org.javers.repository.mongo.MongoRepository.getMongoSnapshotsCursor(MongoRepository.java:280)
2023-03-09T16:46:46.297990067Z  at org.javers.repository.mongo.MongoRepository.getLatest(MongoRepository.java:377)
2023-03-09T16:46:46.297994167Z  at org.javers.repository.mongo.MongoRepository.lambda$new$0(MongoRepository.java:90)
2023-03-09T16:46:46.297998267Z  at org.javers.repository.mongo.LatestSnapshotCache.getLatest(LatestSnapshotCache.java:39)
2023-03-09T16:46:46.298002368Z  at org.javers.repository.mongo.MongoRepository.getLatest(MongoRepository.java:123)
2023-03-09T16:46:46.298006468Z  at org.javers.repository.api.JaversRepository.lambda$getLatest$0(JaversRepository.java:80)
2023-03-09T16:46:46.298010668Z  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2023-03-09T16:46:46.298014768Z  at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
2023-03-09T16:46:46.298018869Z  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2023-03-09T16:46:46.298022969Z  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2023-03-09T16:46:46.298026969Z  at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
2023-03-09T16:46:46.298030869Z  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2023-03-09T16:46:46.298034769Z  at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
2023-03-09T16:46:46.298038470Z  at org.javers.repository.api.JaversRepository.getLatest(JaversRepository.java:83)
2023-03-09T16:46:46.298042770Z  at org.javers.repository.api.JaversExtendedRepository.getLatest(JaversExtendedRepository.java:98)
2023-03-09T16:46:46.298051070Z  at org.javers.core.snapshot.SnapshotGraphFactory.createLatest(SnapshotGraphFactory.java:25)
2023-03-09T16:46:46.298054971Z  at org.javers.core.commit.CommitFactory.createCommit(CommitFactory.java:75)
2023-03-09T16:46:46.298058671Z  at org.javers.core.commit.CommitFactory.create(CommitFactory.java:70)
2023-03-09T16:46:46.298064871Z  at org.javers.core.JaversCore.commit(JaversCore.java:87)
2023-03-09T16:46:46.298079172Z  at org.javers.spring.auditable.aspect.JaversCommitAdvice.commitObject(JaversCommitAdvice.java:93)
2023-03-09T16:46:46.298083672Z  at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
2023-03-09T16:46:46.298087672Z  at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
2023-03-09T16:46:46.298092073Z  at org.javers.spring.auditable.aspect.springdata.AbstractSpringAuditableRepositoryAspect.lambda$onSave$0(AbstractSpringAuditableRepositoryAspect.java:28)
2023-03-09T16:46:46.298095973Z  at java.base/java.util.Optional.ifPresent(Optional.java:178)
2023-03-09T16:46:46.298100173Z  at org.javers.spring.auditable.aspect.springdata.AbstractSpringAuditableRepositoryAspect.onSave(AbstractSpringAuditableRepositoryAspect.java:27)
2023-03-09T16:46:46.298104673Z  at org.javers.spring.auditable.aspect.springdata.JaversSpringDataAuditableRepositoryAspect.onSaveExecuted(JaversSpringDataAuditableRepositoryAspect.java:44)
2023-03-09T16:46:46.298108674Z  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-03-09T16:46:46.298112974Z  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-03-09T16:46:46.298116774Z  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-03-09T16:46:46.298120774Z  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-03-09T16:46:46.298124874Z  at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
2023-03-09T16:46:46.298128975Z  at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:617)
2023-03-09T16:46:46.298132975Z  at org.springframework.aop.aspectj.AspectJAfterReturningAdvice.afterReturning(AspectJAfterReturningAdvice.java:66)
2023-03-09T16:46:46.298136875Z  at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:58)
2023-03-09T16:46:46.298140675Z  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
2023-03-09T16:46:46.298144476Z  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
2023-03-09T16:46:46.298148576Z  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
2023-03-09T16:46:46.298152576Z  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
2023-03-09T16:46:46.298156876Z  at jdk.proxy2/jdk.proxy2.$Proxy124.save(Unknown Source)
```

I know that Cosmos defines a translation layer to provide an interface similar to Mongo, but its internals differ. I believe that the problem is associated to a different internal management of indexes, probably the one associated to the commit timestamp. The number and general structure of indexes is the same in both my local Mongo deployment as well as in the Azure one.   

I'm running with Java 1.17 OpenJDK, javers-spring-boot-starter-mongo 6.11.0, Cosmos Server Version 4.2. 

Does any of you managed to use Javers with Cosmos MongoDB? Do you have any idea how to fix this? 

Thank you and have a a nice day!

**Comment by egasimov** [comment]
Hi, I've integrated Javers with CosmosDB. As I remember, an issue was resolved after using wildcard index.

Sample configuration of indexes used by CosmosDB
```
    jv_head_id                    = { indices = [{ keys : ["$**"] }, ] }
    jv_snapshots                  = { indices = [{ keys : ["globalId_key"] }, { keys : ["globalId.valueObject"] }, { keys : ["globalId.entity"] }, { keys : ["globalId.ownerId.entity"] }, { keys : ["changedProperties"] }, { keys : ["commitMetadata.properties.$**"] } ] }

```

**Comment by bartoszwalacik** [comment]
@egasimov thanks for sharing that, @StefanoConoci does it solve your issue?

**Comment by StefanoConoci** [comment]
Hi, thank your for you feedback @egasimov.

I tried to add the wildcard index commitMetadata.properties.$**, which however did not solve the issue. 

However, I noticed that for my version of Javers the commit information (id, commitDate and commitDateInstant) are put in the commitMetadata object, and not in the commitMetadata.properties sub-object. Given this finding, I added the wildcard index commitMetadata.$** and everything started to work as expected!
