### ISSUE TITLE
Cannot register interface Id property

### ISSUE THREAD

**Issue by bojanv55** [javers/javers#183]
I have interface that is implemented twice:

    public interface MyInter {
        int getId();

        enum Name implements MyInter {
            private int id;
            public int getId(){}
        }

        class MyInterFactory implements MyInter {
            private int id;
            public int getId(){}
        }
    }

I registered the implementations as Entities:

    .registerEntity(new EntityDefinition(MyInter.Name.class, "id"))
    .registerEntity(new EntityDefinition(MyInter.MyInterFactory.class, "id"))

The problem is that interface is recognized as 

    ValueObjectType{
      baseType: MyInter
      managedProperties:
    }

and since it is used in a HashMap, I cannot use it as a key (it needs to be an entity).

    VALUE_OBJECT_IS_NOT_SUPPORTED_AS_MAP_KEY JaVers runtime error - found ValueObject on KEY position in Map property

**Comment by bojanv55** [comment]
I fixed the issue, by commenting this lines :)

      @Override
    public boolean supports(JaversType propertyType) {
        if (!(propertyType instanceof MapType)){
            return false;
        }

        MapContentType mapContentType =   typeMapper.getMapContentType((MapType)propertyType);
    //        if (mapContentType.getKeyType() instanceof ValueObjectType){
    //            throw new JaversException(VALUE_OBJECT_IS_NOT_SUPPORTED_AS_MAP_KEY,
    //                                      propertyType);
    //        }
        return true;
    }

**Comment by bartoszwalacik** [comment]
ok, but this doesn't solve the problem,
so as far as I understand, the issue is that you cannt register your enum type as Javers Entity? That's interesting, i didn't tested enums in such way ...

**Comment by bojanv55** [comment]
Well, in fact, it solved the problem for me.

**Comment by bartoszwalacik** [comment]
ok, but I'm not going to remove these lines :)
First, i dont understand why you trying to change mapping for enums? All enums should be mapped by Javers as PrimitiveTypes by default.

**Comment by bojanv55** [comment]
Well since enums in java are more-less same as other classes I'm using them for partial entity loading. Suppose that in database you have a table of 100 sport names, but in code you only need 2 of them for comparison like "if Sport.SOCCER=array[0].getSport()". That factory serves as loader for 98 sport names from databse and enum serves as holder for 2 hardcoded versions. Everything then can be stored in single list because of polymorphism.

One question - why are you treating interface as value object when it cannot be instantiated anyway?

**Comment by bartoszwalacik** [comment]
well, mixing enums with entities looks like a corner case for me, i never heard about this approach. By definition, enum instances are predefined, and comparing their properties looks strange for me.

JaVers compares enums like primitives, using equals(), and I'm not going to change this strategy.
Can we focus on the problem, that JaVers maps your enums as ValueObjectType?
As I said before, enums should be mapped as PrimitiveTypes.

I suppose, that the reason coud be that your enums implements some interface (which is quite unusual).
This could confuse Javers type inferring algorithm. 
I can check why they are not mapped as PrimitiveTypes but I need a failing test which reproduces the issue (you can write it on Javers fork).

Answering your question, Javers does not treats interfaces as ValueObjectTypes. ValueObjectType is default type for classes without any hints (annotations or explicit mapping in JaversBuilder)

**Comment by bojanv55** [comment]
If something looks strange, doesn't mean you should not support it... Enum in Java is just another class with special treatment. Since it can have a ton of additional properties, you should support those also...

But my problems are not the Enums. It is the error that I'm getting because your code is trying to find properties on an interface. Interface that is used as a key in a Map. Since interface implementations are the only ones used at the runtime as a key, I don't know why you are checking the interface at all. As soon as I commented those lines, I can use my code normally (I want to say that it works then). You should not definitely remove those lines, just remove Interface checking process and check properties on real runtime implementations.

**Comment by bartoszwalacik** [comment]
So you are requesting a feature that Javers should allow mapping enums as EntityTypes? What is the purpose of this feature? What it gives to Javers users?

**Comment by bartoszwalacik** [comment]
@bojanv55 , are we doing sth with this issue?

**Comment by bartoszwalacik** [comment]
closing due to lack of activity
