### ISSUE TITLE
CANT_SAVE_ALREADY_PERSISTED_COMMIT 

### ISSUE THREAD

**Issue by lavpost** [javers/javers#186]
Hi,
when I am running JMeter test (creating books in a loop - author,title,pages -  random values), with number of threads greater than one, once in a while I get this error in eclipse console:

```

org.javers.common.exception.JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit
	at org.javers.repository.sql.JaversSqlRepository.persist(JaversSqlRepository.java:48)
	at org.javers.repository.api.JaversExtendedRepository.persist(JaversExtendedRepository.java:110)
	at org.javers.core.JaversCore.commit(JaversCore.java:62)
	at org.javers.spring.jpa.JaversTransactionalDecorator.commit(JaversTransactionalDecorator.java:48)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy85.commit(Unknown Source)
	at org.javers.spring.auditable.aspect.OnSaveAuditChangeHandler.handle(OnSaveAuditChangeHandler.java:17)
	at org.javers.spring.auditable.aspect.JaversAuditableRepositoryAspect.applyVersionChange(JaversAuditableRepositoryAspect.java:93)
	at org.javers.spring.auditable.aspect.JaversAuditableRepositoryAspect.applyVersionChanges(JaversAuditableRepositoryAspect.java:88)
	at org.javers.spring.auditable.aspect.JaversAuditableRepositoryAspect.onVersionEvent(JaversAuditableRepositoryAspect.java:70)
	at org.javers.spring.auditable.aspect.JaversAuditableRepositoryAspect.onSaveExecuted(JaversAuditableRepositoryAspect.java:58)
	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:603)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:46)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy75.save(Unknown Source)
	at com.monika.jpa.servicesImpl.BookServiceImpl.addBook(BookServiceImpl.java:50)
	at com.monika.jpa.controllers.BookController.createBookRest(BookController.java:80)
	at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

```
This is simple spring boot+hibernate+postgresql application with ```@JaversSpringDataAuditable``` annotations, javers core,spring and hibernate version 1.3.1

BookController - createBookRest method: 

 ```	

    @RequestMapping(value = "/book", method = RequestMethod.POST, produces = "application/json", consumes = "application/json")
    @ResponseBody
	public BookDTO createBookRest(@RequestBody BookDTO book) {

		return bookService.addBook(book);
	}

 ```

and BookServiceImpl - addBook method: 

```	

      public BookDTO addBook(BookDTO book) {

		Book bookEntity = bookDAO.save(new Book(book.getTitle(), book
				.getAuthor(), book.getPages()));
		book.setId(bookEntity.getId());
		return book;
	}

 ```

**Comment by bartoszwalacik** [comment]
looks like a commit id collision. Could you post a logger outpout. On the INFO level, there should be messages with subsequent commid identifiers.

**Comment by lavpost** [comment]
```

2015-08-06 15:36:08.183  INFO 4204 --- [io-8080-exec-22] org.javers.core.Javers                   : Commit(id:33595.31, snapshots:3, author:unknow, changes - NewObject:2 ValueChange:4 ReferenceChange:2)
2015-08-06 15:36:08.198  INFO 4204 --- [io-8080-exec-33] org.javers.core.Javers                   : Commit(id:33595.24, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.214  INFO 4204 --- [io-8080-exec-30] org.javers.core.Javers                   : Commit(id:33595.33, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.214  INFO 4204 --- [io-8080-exec-45] org.javers.core.Javers                   : Commit(id:33595.39, snapshots:3, author:unknow, changes - NewObject:2 ValueChange:4 ReferenceChange:2)
2015-08-06 15:36:08.214  INFO 4204 --- [io-8080-exec-17] org.javers.core.Javers                   : Commit(id:33595.20, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.229  INFO 4204 --- [io-8080-exec-51] org.javers.core.Javers                   : Commit(id:33595.38, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.229  INFO 4204 --- [io-8080-exec-41] org.javers.core.Javers                   : Commit(id:33595.32, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.245  INFO 4204 --- [io-8080-exec-49] org.javers.core.Javers                   : Commit(id:33595.46, snapshots:3, author:unknow, changes - NewObject:2 ValueChange:4 ReferenceChange:2)
2015-08-06 15:36:08.245  INFO 4204 --- [nio-8080-exec-9] org.javers.core.Javers                   : Commit(id:33595.35, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.307 ERROR 4204 --- [io-8080-exec-36] c.m.jpa.servicesImpl.BookServiceImpl     : JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit
2015-08-06 15:36:08.354  INFO 4204 --- [nio-8080-exec-1] org.javers.core.Javers                   : Commit(id:33595.21, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.354  INFO 4204 --- [io-8080-exec-43] org.javers.core.Javers                   : Commit(id:33595.26, snapshots:4, author:unknow, changes - NewObject:4)
2015-08-06 15:36:08.479  INFO 4204 --- [io-8080-exec-16] org.javers.core.Javers                   : Commit(id:33595.41, snapshots:3, author:unknow, changes - NewObject:2 ValueChange:4 ReferenceChange:2)
2015-08-06 15:36:08.495  INFO 4204 --- [io-8080-exec-44] org.javers.core.Javers                   : Commit(id:33595.42, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.495  INFO 4204 --- [io-8080-exec-28] org.javers.core.Javers                   : Commit(id:33595.15, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.510 ERROR 4204 --- [io-8080-exec-20] c.m.jpa.servicesImpl.BookServiceImpl     : JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit
2015-08-06 15:36:08.541 ERROR 4204 --- [io-8080-exec-31] c.m.jpa.servicesImpl.BookServiceImpl     : JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit
2015-08-06 15:36:08.541 ERROR 4204 --- [io-8080-exec-47] c.m.jpa.servicesImpl.BookServiceImpl     : JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit
2015-08-06 15:36:08.557  INFO 4204 --- [io-8080-exec-19] org.javers.core.Javers                   : Commit(id:33595.43, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.573  INFO 4204 --- [io-8080-exec-24] org.javers.core.Javers                   : Commit(id:33595.36, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.573  INFO 4204 --- [io-8080-exec-40] org.javers.core.Javers                   : Commit(id:33595.10, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.604  INFO 4204 --- [io-8080-exec-34] org.javers.core.Javers                   : Commit(id:33594.22, snapshots:4, author:unknow, changes - NewObject:4)
2015-08-06 15:36:08.635  INFO 4204 --- [io-8080-exec-23] org.javers.core.Javers                   : Commit(id:33595.9, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.744 ERROR 4204 --- [nio-8080-exec-9] c.m.jpa.servicesImpl.BookServiceImpl     : JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit
2015-08-06 15:36:08.744  INFO 4204 --- [nio-8080-exec-7] org.javers.core.Javers                   : Commit(id:33595.40, snapshots:7, author:unknow, changes - NewObject:7)
2015-08-06 15:36:08.775 ERROR 4204 --- [io-8080-exec-27] c.m.jpa.servicesImpl.BookServiceImpl     : JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit
2015-08-06 15:36:08.869  INFO 4204 --- [nio-8080-exec-4] org.javers.core.Javers                   : Commit(id:33595.14, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.869  INFO 4204 --- [io-8080-exec-35] org.javers.core.Javers                   : Commit(id:33595.44, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:08.947 ERROR 4204 --- [io-8080-exec-15] c.m.jpa.servicesImpl.BookServiceImpl     : JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit
2015-08-06 15:36:08.978  INFO 4204 --- [io-8080-exec-50] org.javers.core.Javers                   : Commit(id:33595.30, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.105  INFO 4204 --- [io-8080-exec-32] org.javers.core.Javers                   : Commit(id:33595.37, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.152  INFO 4204 --- [nio-8080-exec-9] org.javers.core.Javers                   : Commit(id:33596.6, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.428 ERROR 4204 --- [io-8080-exec-28] c.m.jpa.servicesImpl.BookServiceImpl     : JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit
2015-08-06 15:36:09.455  INFO 4204 --- [io-8080-exec-35] org.javers.core.Javers                   : Commit(id:33596.9, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.487  INFO 4204 --- [io-8080-exec-23] org.javers.core.Javers                   : Commit(id:33596.10, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.523  INFO 4204 --- [io-8080-exec-19] org.javers.core.Javers                   : Commit(id:33596.11, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.555  INFO 4204 --- [nio-8080-exec-6] org.javers.core.Javers                   : Commit(id:33596.8, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.617  INFO 4204 --- [nio-8080-exec-2] org.javers.core.Javers                   : Commit(id:33594.21, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.648  INFO 4204 --- [io-8080-exec-39] org.javers.core.Javers                   : Commit(id:33595.29, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.711  INFO 4204 --- [nio-8080-exec-5] org.javers.core.Javers                   : Commit(id:33596.12, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.773  INFO 4204 --- [io-8080-exec-38] org.javers.core.Javers                   : Commit(id:33595.28, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.773  INFO 4204 --- [nio-8080-exec-3] org.javers.core.Javers                   : Commit(id:33595.23, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.789  INFO 4204 --- [io-8080-exec-44] org.javers.core.Javers                   : Commit(id:33596.13, snapshots:3, author:unknow, changes - NewObject:3)
2015-08-06 15:36:09.820 ERROR 4204 --- [nio-8080-exec-8] c.m.jpa.servicesImpl.BookServiceImpl     : JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit
2015-08-06 15:36:09.836  INFO 4204 --- [io-8080-exec-13] org.javers.core.Javers                   : Commit(id:33595.18, snapshots:3, author:unknow, changes - NewObject:3)

```

**Comment by bartoszwalacik** [comment]
fixed in release 1.3.2

**Comment by bartoszwalacik** [comment]
http://javers.org/documentation/features/#release-notes

**Comment by lavpost** [comment]
When I started testing my app with the newest version, the same error occured. Less often than in the previous one, though it still exists.

```


2015-08-10 11:10:17.948  INFO 5840 --- [io-8080-exec-10] org.javers.core.Javers                   : Commit(id:183998.1, snapshots:1, author:unknow, changes - NewObject:1)
2015-08-10 11:10:17.948 ERROR 5840 --- [io-8080-exec-18] c.m.jpa.servicesImpl.BookServiceImpl     : JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit '183991.0'
2015-08-10 11:10:18.104  INFO 5840 --- [io-8080-exec-11] org.javers.core.Javers                   : Commit(id:183999.1, snapshots:1, author:unknow, changes - NewObject:1)
2015-08-10 11:10:18.104  INFO 5840 --- [io-8080-exec-10] org.javers.core.Javers                   : Commit(id:183999.0, snapshots:1, author:unknow, changes - NewObject:1)


```

after about two hours of constant testing the error  disappeared(jMeter -50 threads 100000 samples then 60 threads 120000 samples - no errors).
When I restarted my computer it showed up again.

```


2015-08-10 14:00:03.118  INFO 224 --- [io-8080-exec-35] org.javers.core.Javers                   : Commit(id:242109.0, snapshots:1, author:unknow, changes - NewObject:1)
2015-08-10 14:00:03.133  INFO 224 --- [io-8080-exec-41] org.javers.core.Javers                   : Commit(id:242103.3, snapshots:1, author:unknow, changes - NewObject:1)
2015-08-10 14:00:03.165 ERROR 224 --- [nio-8080-exec-4] c.m.jpa.servicesImpl.BookServiceImpl     : JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit '242104.0'
2015-08-10 14:00:03.165  INFO 224 --- [nio-8080-exec-1] org.javers.core.Javers                   : Commit(id:242110.0, snapshots:1, author:unknow, changes - NewObject:1)
2015-08-10 14:00:03.165 ERROR 224 --- [io-8080-exec-12] c.m.jpa.servicesImpl.BookServiceImpl     : JaversException: CANT_SAVE_ALREADY_PERSISTED_COMMIT JaVers runtime error - can't save already persisted commit '242104.1'
2015-08-10 14:00:03.165  INFO 224 --- [io-8080-exec-48] org.javers.core.Javers                   : Commit(id:242110.1, snapshots:1, author:unknow, changes - NewObject:1)
2015-08-10 14:00:03.227  INFO 224 --- [io-8080-exec-24] org.javers.core.Javers                   : Commit(id:242111.0, snapshots:1, author:unknow, changes - NewObject:1)


```

I also came across  ``` sequenceLimitReachedException ```

```


2015-08-10 09:14:36.874  INFO 5576 --- [io-8080-exec-42] org.javers.core.Javers                   : Commit(id:179781.1, snapshots:1, author:unknow, changes - NewObject:1)
2015-08-10 09:14:36.889  INFO 5576 --- [io-8080-exec-18] org.javers.core.Javers                   : Commit(id:179781.3, snapshots:1, author:unknow, changes - NewObject:1)
2015-08-10 09:14:36.921 ERROR 5576 --- [io-8080-exec-37] c.m.jpa.servicesImpl.BookServiceImpl     : org.polyjdbc.core.exception.SequenceLimitReachedException: [SEQUENCE_LIMIT_REACHED] Sequence jv_snapshot_pk_seq has reached its limit of 454699. Before fetching value, check if recalculation is needed using recalculationNeeded() method.
2015-08-10 09:14:36.921  INFO 5576 --- [io-8080-exec-31] org.javers.core.Javers                   : Commit(id:179782.2, snapshots:1, author:unknow, changes - NewObject:1)
2015-08-10 09:14:36.936  INFO 5576 --- [io-8080-exec-19] org.javers.core.Javers                   : Commit(id:179782.0, snapshots:1, author:unknow, changes - ValueChange:4)

```

**Comment by bartoszwalacik** [comment]
I've tested on 20 threds, will try to reproduce this error again and then tuning queue size in SeqGenerator should work

**Comment by bartoszwalacik** [comment]
I've pushed next fix which should solve the problem finally,
tested on 100 threads doing concurrent writes.

Available in 1.3.3-SNAPSHOT published at
https://oss.sonatype.org/content/repositories/snapshots/

could you check it out?

**Comment by bartoszwalacik** [comment]
Released in javers 1.3.3
