### ISSUE TITLE
Map dot key replacement

### ISSUE THREAD

**Issue by rebel23** [javers/javers#416]
Map fields of object snapshots containing keys with dots cannot be persisted.
It would be perfect to add possibility to set map key dot replacement ('.' <> '#dot#' for example) in Javers MongoRepository or Javers at all.

**Comment by rebel23** [comment]
Hi, completely forgot about test case, sorry. 
I've just added a case to JaversMongoRepositoryE2ETest, so now MongoIntegrationTest should fail on it. Unfortunately I couldn't run this test on my local machine. Please, confirm if you can reproduce the issue.
Here is the link to branch with test case in my fork: [issue416](https://github.com/rebel23/javers/tree/issue416)

**Comment by bartoszwalacik** [comment]
ok, will check it next week (now I'm on holiday)

**Comment by bartoszwalacik** [comment]
fixed in 2.1.2

**Comment by rebel23** [comment]
It looks great) But this solution does not work for nested maps, still getting the same exception:
`def version2 = new SnapshotEntity(id: 1, polymorficMap: ['key':['primitive.value':1]])`
`javers.commit('author', version2)`
`snapshots[0].getPropertyValue('polymorficMap') == ['key':['primitive.value':1]]`
I've update branch in my fork with this case.

**Comment by bartoszwalacik** [comment]
true, but I don't  think that JaVers will do meaningful diff for such complex structure like
`Map<?,Map<String,?>`. 
I suggest replacing nested Map with some ValueObject class

**Comment by rebel23** [comment]
You are right. Thank you for suggestion and quick fix!
